config/routes.rb
Rails.application.routes.draw do
  resources :cal_taxes do
    collection do
      get "calc"
    end
  end
end

app/models/cal_tax.rb
class CalTax < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cal_taxes_controller.rb
class CalTaxesController < ApplicationController
  before_action :set_cal_tax, only: [:show, :edit, :update, :destroy]

  # GET /cal_taxes
  # GET /cal_taxes.json
  def index
    @cal_taxes = CalTax.all
  end

  # GET /cal_taxes/1
  # GET /cal_taxes/1.json
  def show
  end

  def calc
  end
  

  # GET /cal_taxes/new
  def new
    @cal_tax = CalTax.new
  end

  # GET /cal_taxes/1/edit
  def edit
  end

  # POST /cal_taxes
  # POST /cal_taxes.json
  def create
    @cal_tax = CalTax.new(cal_tax_params)

    respond_to do |format|
      if @cal_tax.save
        format.html { redirect_to @cal_tax, notice: 'Cal tax was successfully created.' }
        format.json { render :show, status: :created, location: @cal_tax }
      else
        format.html { render :new }
        format.json { render json: @cal_tax.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cal_taxes/1
  # PATCH/PUT /cal_taxes/1.json
  def update
    respond_to do |format|
      if @cal_tax.update(cal_tax_params)
        format.html { redirect_to @cal_tax, notice: 'Cal tax was successfully updated.' }
        format.json { render :show, status: :ok, location: @cal_tax }
      else
        format.html { render :edit }
        format.json { render json: @cal_tax.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cal_taxes/1
  # DELETE /cal_taxes/1.json
  def destroy
    @cal_tax.destroy
    respond_to do |format|
      format.html { redirect_to cal_taxes_url, notice: 'Cal tax was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cal_tax
      @cal_tax = CalTax.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cal_tax_params
      params.require(:cal_tax).permit(:withtax, :withouttax)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cal_taxes_helper.rb
module CalTaxesHelper
end

app/views/cal_taxes/_calc.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'/>
        <title>じゅん豚</title>
        <style>
            body{font:12px/1.2 Verdana, sans-serif; padding:0 10px;}
            a:link, a:visited{text-decoration:none; color:#416CE5; border-bottom:1px solid #416CE5;}
            h2{font-size:13px; margin:15px 0 0 0;}
        </style>
 
    </head>
    <body>
        <h1>Jun Igami Color Box</h1>

        <p><a id="calc" href="/cal_taxes/calc">計算</a></p>

<script>
$("#calc").colorbox();
</script>
    </body>
</html>

app/views/cal_taxes/_form.html.erb
<%= form_for(@cal_tax) do |f| %>
  <% if @cal_tax.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cal_tax.errors.count, "error") %> prohibited this cal_tax from being saved:</h2>

      <ul>
      <% @cal_tax.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= render "calc" %>
  <div class="field">
    <%= f.label :withtax %><br>
    <%= f.number_field :withtax %>
  </div>
  <div class="field">
    <%= f.label :withouttax %><br>
    <%= f.number_field :withouttax %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cal_taxes/calc.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'/>
        <title>計算画面</title>
        <style>
            body{font:12px/1.2 Verdana, sans-serif; padding:0 10px;}
            a:link, a:visited{text-decoration:none; color:#416CE5; border-bottom:1px solid #416CE5;}
            h2{font-size:12px; margin:15px 0 0 0;}
        </style>
        <link rel="stylesheets" href="/asset/stylesheets/colorbox.css"/>
        <link rel="stylesheets" href="/asset/stylesheets/custom.css"/>
        <script>
            var excludingTaxPrice;

            // $(document).ready(function(){
                // var includingTaxPrice = $('#shopInfo [name="includingTax"]').val();
                // $(".includingTax2").text("¥" + includingTaxPrice);
                
                
            // });

            $("#calcExcludingTax").on("click", function(){
                var includingTaxPrice = $("#includingTax2").val()
                excludingTaxPrice = 
                Math.floor(Number(includingTaxPrice) / 1.08);  
                // $(".excludingTax2").text("¥" + String(excludingTaxPrice));
                $(".includingTax").val(excludingTaxPrice);
                $('#cboxClose').click()
            });

        </script>
    </head>
    <body>
        <div class="wrapper">
            <p>税込価格</p>
            <input type="textbox" id="includingTax2" class="includngTax2" placeholder="ex) 10000">
            <!-- <p class="includingTax2"</p> -->
            <br />
            <br />
            <br />
            <!-- <p>税抜価格</p>
            <p class="excludingTax2"></p>
            <br /> -->
            <input type ="button" class="closeWindow" value="税抜価格を計算する" id="calcExcludingTax">
        </div>
    </body>
</html>

app/views/cal_taxes/edit.html.erb
<h1>Editing cal_tax</h1>

<%= render 'form' %>

<%= link_to 'Show', @cal_tax %> |
<%= link_to 'Back', cal_taxes_path %>

app/views/cal_taxes/index.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'/>
        <title>税抜き計算</title>
        <style>
            body{font:12px/1.2 Verdana, sans-serif; padding:0 10px;}
            a:link, a:visited{text-decoration:none; color:#416CE5; border-bottom:1px solid #416CE5;}
            h2{font-size:13px; margin:15px 0 0 0;}
        </style>
</head>

    <body>
        <form action="#" method="POST" id="shopInfo">
            <label for="includingTax">税抜価格</label>
            <input name="includingTax" class="includingTax" type="textbox" placeholder="ex) 10000">円
            <input type="button" class="excludingTax" value="税込価格から税抜価格を計算する" href='#'>     
        </form>



<!-- ↑元indexのコード ↓統合させるための新たな記述-->
        <script>
            $(document).ready(function(){
                var tmpl = $("#colorbox_tmpl");
                $(".excludingTax").colorbox({
                    rel:'excludingTax', 
                    html: tmpl.html(),
                    closeButton: false,
                    onComplete:function(){
                        var priceFromForm = $(".includingTax").val()
                        $("#includingTax2").val(priceFromForm);

                        $("#calcExcludingTax").on("click", function(){
                            var includingTaxPrice = $("#includingTax2").val()
                            excludingTaxPrice = Math.floor(Number(includingTaxPrice) / 1.08);  
                            $(".includingTax").val(excludingTaxPrice);
                            });
                        }
                    });
                });
        </script>
        <script id="colorbox_tmpl" type="text/x-spmkt">
        <div class="wrapper">
            <p>税込価格</p>
            <input type="textbox" id="includingTax2" class="includngTax2" placeholder="ex) 10000">
            <br />
            <br />
            <input type="button" class="closeWindow" value="税抜価格を計算する" id="calcExcludingTax" onClick="parent.$.colorbox.close();" href="#">
            </div>
        </script>         
    </body>
</html>

app/views/cal_taxes/index2.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'/>
        <title>税抜き計算</title>
        <style>
            body{font:12px/1.2 Verdana, sans-serif; padding:0 10px;}
            a:link, a:visited{text-decoration:none; color:#416CE5; border-bottom:1px solid #416CE5;}
            h2{font-size:13px; margin:15px 0 0 0;}
        </style>
        <link rel="stylesheet" href="colorbox.css" />
        <script src="jquery.min.js"></script>
        <script src="jquery.cookie.js"></script>
        <script src="jquery.colorbox.js"></script>
        <script>
            $(document).ready(function(){
                $(".excludingTax").colorbox({rel:'excludingTax'});
            });
        </script>
    </head>
    <body>
        <form action="#" method="POST" id="shopInfo">
            <label for="includingTax">税込み価格を入力してください</label>
            <input name="includingTax" class="includingTax" type="textbox" placeholder="ex) 10000">円
            <p><a class="excludingTax" href="calc.html">上記の税抜き価格を計算する</a></p>
        </form>
        <script>
            $('.excludingTax').click(function() {
                $.cookie('price', $('#shopInfo [name="includingTax"]').val());
            });
        </script>
    </body>
</html>

app/views/cal_taxes/new.html.erb
<h1>New cal_tax</h1>

<%= render 'form' %>

<%= link_to 'Back', cal_taxes_path %>




<%#
可能性
1 http://ruby-rails.hatenadiary.com/entry/20140807/1407419013#render-view-desc  4
部分テンプレ
2render file: ~~~~~~~~


	%>

app/views/cal_taxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Withtax:</strong>
  <%= @cal_tax.withtax %>
</p>

<p>
  <strong>Withouttax:</strong>
  <%= @cal_tax.withouttax %>
</p>

<%= link_to 'Edit', edit_cal_tax_path(@cal_tax) %> |
<%= link_to 'Back', cal_taxes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sm5</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>